apiVersion: v1
kind: Service
metadata:
  name: staging-app-${K8S_PROJECT}
  namespace: ${K8S_NS}
  labels:
    project: ${K8S_PROJECT}
    env: staging
    app: app
spec:
  selector:
    project: ${K8S_PROJECT}
    env: staging
    app: app
  ports:
    - protocol: TCP
      port: 8080
